version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: northwind
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mariadb_db
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 7777:8080